{% set name = "presamples" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cec2dc121b21b1e52d03ea1b19955407d3609be6e5459d50feda4cdf737054f6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - bw2calc
    - bw2data
    - numpy
    - peewee
    - python >={{ python_min }}
    - scipy
    - stats_arrays
    - wrapt

test:
  requires:
    - python {{ python_min }}
  imports:
    - presamples

about:
  home: https://github.com/PascalLesage/presamples
  summary: 'Package to write, load, manage and verify numerical arrays, called presamples.'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://presamples.readthedocs.io
  dev_url: https://github.com/PascalLesage/presamples

extra:
  recipe-maintainers:
    - cmutel
    - m-rossi
